services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Password"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    healthcheck:
      test: [ "CMD", "/opt/mssql-tools/bin/sqlcmd", "-U", "sa", "-P", "Password", "-Q", "SELECT 1" ]
      interval: 10s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Target/Dockerfile
    depends_on:
      sqlserver:
        condition: service_healthy
    ports:
      - "5068:80"
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=TargetDb;User Id=sa;Password=Password;TrustServerCertificate=True;